region = {
    'argentina': 'arg',
    'bolivia': 'bol',
    'brazil': 'braz',
    'chile': 'chil',
    'colombia': 'col',
    'denmark': 'den',
    'finland': 'fin',
    'indonesia': 'infon',
    'israel': 'israel',
    'malaysia': 'malay',
    'mexico': 'mex',
    'norway': 'norw',
    'peru': 'peru',
    'philippines': 'phlns',
    'spain': 'spain',
    'sweden': 'swed',
    'thailand': 'thail',
    'turkey': 'turk',
    'uruguay': 'uru',
    'venezuela': 'ven'
}